import { GoogleGenAI } from "@google/genai";
import { AIInsightData } from '../types';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

export const getHealthInsights = async (data: AIInsightData): Promise<string> => {
  try {
    const prompt = `
      Analyze the following personal health data and provide non-diagnostic, wellness-focused insights.
      The user is looking for general observations, potential areas for improvement, and actionable recommendations for a healthier lifestyle.
      IMPORTANT: This is not medical advice. Start your response with a clear disclaimer: "Disclaimer: This analysis is generated by an AI and is for informational purposes only. It is not a substitute for professional medical advice. Please consult with a healthcare provider for any health concerns."

      User's Health Data:
      - Resting Heart Rate: ${data.heartRate || 'Not provided'} bpm
      - Blood Pressure (Systolic/Diastolic): ${data.bloodPressure || 'Not provided'} mmHg
      - Recent Healthy Activity: ${data.activityType ? `${data.activityType} for ${data.activityDuration} minutes` : 'Not provided'}
      - Hours of Sleep Last Night: ${data.sleepHours || 'Not provided'} hours
      - General Notes/Feelings: ${data.notes || 'Not provided'}

      Based on this data, please:
      1. Provide actionable and quantifiable recommendations for improvement. For example, suggest increasing sleep by 'X minutes' or aiming for 'Y more minutes' of activity per week.
      2. Suggest 1-2 simple, relevant mindfulness exercises or stretches based on the user's reported feelings or activity levels.

      Please structure your response in a clear, encouraging, and easy-to-understand format. Use markdown for formatting (e.g., headings, bullet points).
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    return response.text;
  } catch (error) {
    console.error("Error fetching health insights from Gemini API:", error);
    return "There was an error generating your health insights. Please check your API key and network connection and try again.";
  }
};